# -*- coding: utf-8 -*-
"""Nutrition data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q3pku8N5tLBm1Q6wYdbpGMvMiolawr2c
"""

# Commented out IPython magic to ensure Python compatibility.
#importing basic libraries
import pandas as pd, numpy as np, seaborn as sns, matplotlib.pyplot as plt
# %matplotlib inline

Nutrition= pd.read_excel('/content/Nutrition data.xlsx')
Nutrition.head(2)

Nutrition.columns

Nutrition.shape

Nutrition.info()

"""## Correlation"""

#correlation
Nutrition.corr()

nutrition1=Nutrition[['Height (feet)',	'Weight (kg)']]
nutrition1.corr()

nutrition2=Nutrition[['Weight (kg)'	,'BMI']]
nutrition2.corr()

nutrition2=Nutrition[['Energy',	'Protein']]
nutrition2.corr()

nutrition3=Nutrition[['Energy',	'Fat']]
nutrition3.corr()

nutrition4=Nutrition[['Protein',	'Fat']]
nutrition4.corr()

nutrition5=Nutrition[['Protein',	'Carbohydrate']]
nutrition5.corr()

nutrition6=Nutrition[['Fat',	'Carbohydrate']]
nutrition6.corr()

nutrition7=Nutrition[['Energy',	'Carbohydrate']]
nutrition7.corr()

Nutrition.plot.scatter(x='Weight (kg)', y='BMI')

Nutrition.hist()
plt.show()

plt.figure(figsize=(15,10))
cor = Nutrition.corr()
sns.heatmap(cor,annot=True, cmap='cividis')

"""## Chi Square"""

import  scipy.stats as stats
from scipy.stats import chi2

ctab1=pd.crosstab(Nutrition['Result'],Nutrition['Result.1']) 
ctab1

ctab1.plot(kind='bar', cmap ='cool')
plt.title('Result', fontdict= {'fontsize':20, 'fontweight':5, 'color':'darkblue'})

alpha=0.05
values=stats.chi2_contingency(ctab1)
values

p_value1=values[1]
p_value1

if p_value1 <= alpha:
   print("Reject H0")
else:
  print("Accept H0")

"""##conclusion

This is a data of body builders.

*    weight and BMI are positively correlated. As weight increases for each body builders there is a chance for they being obese.  

*    protein and energy are moderate positive correlated, in this data as they are not taking high protein cotent food so that they are gaining moderate energy.

*    fat and energy are moderately positive correlated, in this data as they are not taking high fat content food so that they are gaining moderate energy.

*    in this data we can see, the here the body builders are taking fat content and protein content foods in a moderate level.to maintain their body building.

*    protein and fat is highly correlated, which means most of the protein content foods have fat ...its accrding to the food type

*    Protein and carbohydrates are highly correlated, beacause obviously in protein foods their is carbohydrates..protein foods are of 2 kind one is pulses and other is Non Veg. in pulses their is not fat but carbohydrate is high.
in Non veg fat is high.

*    fat and carbohydrates are moderately correlated, 

*    Energy and carbohydrates ate moderately correlated. as we take more carbohydrates their is no chance of getting energy. in this data bodybuiders are tking not much carbohydrates and they are not gainig energy from carbohydrate foods.

*   in this data the body buliders are not taking much fat foods. insted of that they take protein powders and weight gainers. in this data to gain energy body builders are mostly taking carbohydrates.

the food items with more protein and fat is having carbohydrates.its vary accoding to the food items we take.









"""